### ISSUE TITLE
A bug whithin the code 

### ISSUE THREAD

**Issue by gautax** [manthan89-py/Real-Time-Social-Media-Content-Retrievel-System#1]
When trying the implement the code as it it, I encounter an issue when trying to ingest data into the vectorDB: 
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'
Traceback:
File "C:\Users\pc\desktop\R-A-G\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "C:\Users\pc\Desktop\R-A-G\app.py", line 101, in <module>
    migrate_data_to_vectordb(username)
File "C:\Users\pc\Desktop\R-A-G\app.py", line 57, in migrate_data_to_vectordb
    run_main(flow)
Before this i encountered another typeError saying the the function run_main needs 5 arguments when only one is given, i was wondering if there is a solution to redirect this error. I appreciate your Help in advance.
I'm working on windows 10 and using python 3.9.13 version if that could help
